### ISSUE TITLE
`.pre-commit-config.yaml`

### ISSUE THREAD

**Issue by Eviato** [padok-team/docs-terraform-guidelines#24]
Following the ROSE convention, the conventional commit should be used.

The [`.pre-commit-config.yaml`](https://github.com/padok-team/docs-terraform-guidelines/blob/main/assets/.pre-commit-config.yaml) can integrate a solution such as [Commitizen](https://github.com/commitizen-tools/commitizen#integrating-with-pre-commit)

```yaml
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.40.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
```
